version: "3.6"
services:
  jupyter:
    build: ./jupyter/
    volumes:
      - ./notebooks:/home/jovyan/notebooks
      - ./datasets:/home/jovyan/datasets
    ports:
      - 8888:8888
    command: jupyter lab
    container_name: jupyter_container

  yolo:
    image: nvidia/cuda:9.0-base
    ports:
     - 8072:80
    
    container_name: yolo_container
